### ISSUE TITLE
hacep performances decrease when size of drools sessions grows

### ISSUE THREAD

**Issue by saimon1982** [redhat-italy/hacep#86]
When drools sessions are empty, hacep works fine with a predefined load (110 evts/sec) distributed on 800 fact key, consuming all facts in jms queue. After few million events, hacep seems to slow down its throughput (about half of initial throughput)and messages on queue begin to accumulate. Looking on hacep code, listener `FactListenerPost` is sync, so when it calls method `saver.insert((Key) key, (Fact) value)` , the thread which triggered the cache event may block until the listener callback completes.

**Comment by ugol** [comment]
Hi Saimon82, FactListenerPost must be sync for consistency reasons (that's not an issue), looks like the JGroups/Infinispan stack must be finely tuned if the put operations start to slow down.

**Comment by saimon1982** [comment]
Ok ugol,
in fact enabling log to debug level, we noticed that the slowest operation is the `put` in the sessions cache once drools session is been updated. How can we optimize this operation?
Thanks

**Comment by ugol** [comment]
I'd say that the easiest thing to try is to bump up JDG dependencies from 7.0 to 7.1 (which is much faster in writings, 60% on average). But from your description I think that you are reaching some other limit, so, though it's important to update to latest version - and we'll do that anyway in upstream - you should analyse the root cause of the slow down too.

**Comment by ugol** [comment]
updated to latest JDG 7.1 bits.

**Comment by jennyna** [comment]
Hi ugol,

looking at infinispan logs set to trace level, the most expensive operation done during the sessionCache.put is the waiting of the ack of the replicated session, that is not a simple ack but the complete HAKieReplicatedSession object (and this should explain the reason of the slow down of the system when sessions become too big, about 5MB serialized).
As far as I can understand, the HAKieReplicatedSession object is not needed to the primary node, so would it be possible to avoid this object to come back and have just an ack? 
Thanks.

**Comment by ugol** [comment]
HA*Session don't travel on the wire, meaning that just the last event travels (HAKieReplicatedSession  implement DeltaAware interface). So the replicas maintain a snapshot and a queue of the events to reapply if needed (if needed == the replica becomes a live object OR we are calculating a new snapshot), and the net effect of this approach is that when you do a put with a Session of 5Mb and an event of 1kb, just the 1kb will travel on the wire and never the full session. So size of sessions don't affect directly the put operations. 
A simple test you can do to understand if the system is suffering doing the snapshots (in which hacep deserialise the replicas) is to increase the parameter grid.buffer (which by default is 1000) to a much bigger value. With the default to 1000 it means that sessions are snapshotted every 1000 events, but if you have some thousands big sessions that could happen frequently on the cluster (more than once per second). 

On the other side, if you want to improve availability of the system and relax consistency, you could do async puts instead of sync puts. But you have to be aware that:
1. you are trading off consistency vs availability
2. big sessions don't travel on the wire

**Comment by saimon1982** [comment]
Hi ugol, 
so when we see this kind of log `remote-thread-hacep-node-p10-t1247 | TRACE | org.infinispan.remoting.transport.jgroups.CommandAwareRpcDispatcher |  About to send back response SuccessfulResponse{responseValue=it.redhat.hacep.cache.session.HAKieSerializedSession@7c9ebae7}  for command SingleRpcCommand{cacheName='___sessions', command=PutKeyValueCommand{key=1-1-899899446205, value=it.redhat.hacep.cache.session.HAKieSessionDeltaFact@5cd73cbc, flags=[DELTA_WRITE], putIfAbsent=false, valueMatcher=MATCH_ALWAYS, metadata=EmbeddedExpirableMetadata{lifespan=-1, maxIdle=-1, version=null}, successful=true}}
` on the node who hold the replicated session, it means that the responseValue object doesn't travel back on the wire to the primary? 
 The `grid.buffer` parameter is specific for a session and not shared for all, it's right?

Thanks
